export const worldEvents = {
    1950: "The Korean War begins as North Korea invades South Korea.",
    1951: "The European Coal and Steel Community is formed, identifying the start of European integration.",
    1952: "Queen Elizabeth II ascends to the British throne.",
    1953: "James Watson and Francis Crick discover the double-helix structure of DNA.",
    1954: "Roger Bannister becomes the first person to run a mile in under four minutes.",
    1955: "Rosa Parks refuses to give up her seat on a bus in Montgomery, Alabama.",
    1956: "The Suez Crisis erupts after Egypt nationalizes the Suez Canal.",
    1957: "The Soviet Union launches Sputnik 1, the first artificial Earth satellite.",
    1958: "NASA is founded in the United States.",
    1959: "The Barbie doll makes its debut at the American International Toy Fair.",
    1960: "The laser is invented by Theodore Maiman.",
    1961: "Yuri Gagarin becomes the first human in space.",
    1962: "The Cuban Missile Crisis brings the world to the brink of nuclear war.",
    1963: "Martin Luther King Jr. delivers his 'I Have a Dream' speech.",
    1964: "The Beatles appear on The Ed Sullivan Show, launching the 'British Invasion'.",
    1965: "The Sound of Music serves as the year's most popular film.",
    1966: "Star Trek premieres on television.",
    1967: "The first heart transplant is performed by Christiaan Barnard.",
    1968: "Apollo 8 becomes the first manned spacecraft to orbit the Moon.",
    1969: "Neil Armstrong becomes the first human to walk on the Moon.",
    1970: "The first Earth Day is celebrated by millions.",
    1971: "Walt Disney World opens in Florida.",
    1972: "Pong, one of the first arcade video games, is released.",
    1973: "The Sydney Opera House is officially opened by Queen Elizabeth II.",
    1974: "The Rubik's Cube is invented by Erno Rubik.",
    1975: "Bill Gates and Paul Allen found Microsoft.",
    1976: "Steve Jobs and Steve Wozniak form Apple Computer.",
    1977: "Star Wars: A New Hope is released, changing cinema forever.",
    1978: "The first 'test tube baby', Louise Brown, is born.",
    1979: "Sony introduces the Walkman, revolutionizing personal music.",
    1980: "Pac-Man is released in Japan and becomes a global phenomenon.",
    1981: "MTV (Music Television) launches, playing 'Video Killed the Radio Star'.",
    1982: "Michael Jackson releases 'Thriller', the best-selling album of all time.",
    1983: "The internet's precursor, ARPANET, officially switches to TCP/IP.",
    1984: "The Apple Macintosh is introduced with its famous '1984' Super Bowl commercial.",
    1985: "Live Aid concerts raise millions for famine relief in Ethiopia.",
    1986: "Halley's Comet makes its once-in-a-lifetime visible return.",
    1987: "Aretha Franklin becomes the first woman inducted into the Rock and Roll Hall of Fame.",
    1988: "The first transatlantic fiber optic cable goes into operation.",
    1989: "The Berlin Wall falls, leading to the reunification of Germany.",
    1990: "The Hubble Space Telescope is launched into orbit.",
    1991: "The World Wide Web becomes publicly available.",
    1992: "The first text message (SMS) is sent ('Merry Christmas').",
    1993: "Jurassic Park breaks box office records with CGI dinosaurs.",
    1994: "Nelson Mandela becomes the first black president of South Africa.",
    1995: "Pixar releases Toy Story, the first feature-length computer-animated film.",
    1996: "Dolly the Sheep becomes the first mammal cloned from an adult cell.",
    1997: "J.K. Rowling publishes 'Harry Potter and the Philosopher's Stone'.",
    1998: "Google is founded in a garage in Menlo Park, California.",
    1999: "The Euro is introduced as a currency in 11 countries.",
    2000: "The Y2K bug passes without major incident.",
    2001: "Wikipedia is launched, changing how the world accesses information.",
    2002: "The Euro enters circulation as physical coins and banknotes.",
    2003: "The Human Genome Project is completed, mapping human DNA.",
    2004: "Facebook is launched by Mark Zuckerberg at Harvard.",
    2005: "YouTube is founded and the first video 'Me at the zoo' is uploaded.",
    2006: "Twitter sends its first tweet: 'just setting up my twttr'.",
    2007: "Steve Jobs unveils the first iPhone.",
    2008: "Barack Obama is elected as the first African-American US President.",
    2009: "Bitcoin, the first cryptocurrency, is created by Satoshi Nakamoto.",
    2010: "Instagram is launched and acquired by Facebook two years later.",
    2011: "The world population hits 7 billion.",
    2012: "The Curiosity rover lands on Mars.",
    2013: "Nelson Mandela passes away at age 95.",
    2014: "The Ice Bucket Challenge goes viral, raising millions for ALS research.",
    2015: "SpaceX successfully lands a reusable orbital rocket for the first time.",
    2016: "Pokemon Go takes over the world as an AR phenomenon.",
    2017: "Cryptocurrency prices soar, bringing Bitcoin to mainstream attention.",
    2018: "Apple becomes the first public company to be worth $1 trillion.",
    2019: "The first ever image of a Black Hole is captured by the Event Horizon Telescope.",
    2020: "The COVID-19 pandemic changes daily life globally.",
    2021: "James Webb Space Telescope is launched to peer into the early universe.",
    2022: "Global population reaches 8 billion people.",
    2023: "Artificial Intelligence (ChatGPT) enters the mainstream consciousness.",
    2024: "SpaceX Starship makes its first successful orbital test flight.",
    2025: "The world looks forward to the next great leap in technology and culture."
};
